package com.arthurscheper.professorcuradortoolkit.domain;

public enum Etapa {
    ANALISAR_PLANO_ENSINO,
    ANALISANDO_PLANO_ENSINO,
    SELECIONAR_BLOCO,
    SELECIONAR_UNIDADE_APRENDIZAGEM,
    DEFINIR_PERFIL_PEDAGOGICO,
    CONFIRMAR_PERFIL_PEDAGOGICO,
    SELECIONAR_FASE_TRILHA,
    ENVIAR_REQUISICAO_FASE_TRILHA,
    CONFIRMACAO_REQUISICAO_FASE_TRILHA,
    REFINAMENTO_PROMPT,
    PROMPT_FINALIZADO
}
